Homework2
dbychkou/test pull request #3
Opened 2023-02-22 21:12 UTC by dbychkou

2023-02-23 12:52 UTC, codci requested changes

2023-02-23 12:52 UTC, codci commented on Resources/openweathermap.robot
> +    Element Should Not Be Visible    //div[contains(text(),'Signed in successfully.')]
Дублируется XPATH локатор

2023-02-23 12:52 UTC, codci commented on Results/log.html
> +<!DOCTYPE html>
Удалить файл репортп и добавить в gitignore

2023-02-23 12:52 UTC, codci commented on Results/output.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Удалить файл репорт и добавить в gitignore

2023-02-23 12:52 UTC, codci commented on Results/report.html
> +<!DOCTYPE html>
Удалить файл репорт и добавить в gitignore

2023-02-23 12:52 UTC, codci commented on Tests/Task2.robot
> +#Login With Invalid Password
удалить комментарий (для уточнения кейса можно добавить блок `[Documentation]`

2023-02-23 12:52 UTC, codci commented on Tests/Task2.robot
> +#Verify User logins to openweathermap
удалить комментарий

2023-02-23 12:52 UTC, codci commented on Resources/openweathermap.robot
> +Login with invalid credentials should fail
лучше всего оставлять template кейворд в том же файле где находится тест которые его использует:
т.к. тесплейт это реализация тест для определенного набора данных у нас не должно быть ситуаций когда мы его переиспользуем в других сценариях (либо это несколько тестов на проверку одной логики с несколькими наборами данных разделаны, но должны находится в одой папке, сьюте)

2023-02-23 12:52 UTC, codci commented on Resources/openweathermap.robot
> +    Invalid Email Or Password Alert Should Be Displayed
проверки сообщения не достаточно в данном случаи т.к. может отображаться сообщение но пользователь все равно авторизуется

2023-02-23 12:52 UTC, codci commented on Tests/Task2.robot
> +Login with valid credentials should pass
сценарий 1 разделен на 2 теста. (валидных / невалидные данные) 
попробуй объединить их в один тест по теплейту

2023-02-27 21:29 UTC, dbychkou commented
[Results.zip](https://github.com/dbychkou/test/files/10844494/Results.zip)

2023-02-27 21:48 UTC, dbychkou commented
[Results.zip](https://github.com/dbychkou/test/files/10844628/Results.zip)

2023-02-28 09:56 UTC, codci commented on Tests/Task2.robot
> +    Sleep    5s
sleep it's a bad approach to wait something as it does not guarantee that event happened after this time and in opposite if event happened pretty fast we just waste test time 

use Explicit Wait instead to wait for a specific event (it this case will be good to use `Wait Until Location Contains` from SeleniumLibrary)

2023-02-28 13:00 UTC, codci approved these changes

2023-02-28 13:00 UTC, merged